### PR TITLE
bthomson seems to have gone away :(

### PR DESCRIPTION
**Pull request by morrowc**
so... here's hoping that blabber/mbox is close to the same.
I'll be testing shortly on my code.

### CODE REVIEW

**Comment by morrowc** [comment]
Oy, this isn't a complete fix, of course, let me add a bit more and see if I can fit blabber's mbox decoding into your model.

**Comment by morrowc** [comment]
These changes aren't exactly correct yet, or my testing isn't working out :)
more work on my part yet to come.

**Comment by rosylilly** [comment]
@morrowc Thank you for pull request. I'm looking forward to it.

**Comment by morrowc** [comment]
howdy! so... I also had to make some changes to:
  github.com/blabber/mbox

so I'm sending a pull request their way as well, once that one is sorted I can check/update this one.
sorry for the delays.

**Comment by morrowc** [comment]
https://github.com/blabber/mbox/issues/4

is the blabber issue.

**Comment by morrowc** [comment]
ok, false alarm for blabber mbox... I simply fixed the problem in mboxparser.go instead :)
I'll update the pull request and then send one last comment here.

**Comment by morrowc** [comment]
Ok, I'm a bit on the fence about the print of the error, it helps ME, but probably just handling that in the calling function is better.

have a look at let me know.

**Comment by morrowc** [comment]
Hey roslilly, I think this is ready for your review.

**Comment by rosylilly** [comment]
@morrowc LGTM. I'll merge it.

**Comment by morrowc** [comment]
At Sat, 25 Feb 2017 06:16:46 -0800,
Sho Kusano <notifications@github.com> wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> Merged #1.
> 

great, thanks! (sorry this got lost in travel mail)
-chris

**Pull request merged**
